// <auto-generated />
namespace NgocTram_2080601170.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class khoitaocacbangCoursevaCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(khoitaocacbangCoursevaCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202303171650511_khoi tao cac bang Course va Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
